name             'librato'
maintainer       'Librato'
maintainer_email 'support@librato.com'
license          'All rights reserved'
description      'Installs/Configures the Librato Agent'
long_description 'Installs/Configures the Librato Agent'
source_url       'https://github.com/librato/chef-librato'
version          '1.1.3'

depends 'yum'
depends 'yum-epel'
depends 'apt'
